<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "doctors".
 *
 * @property int $id
 * @property string|null $name
 * @property string $exp_edu_detail
 * @property string $phone
 * @property string $tel
 * @property string $timing
 * @property string $header_detail
 * @property string $address
 * @property string $created_at
 */
class Doctors extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'doctors';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['exp_edu_detail', 'phone', 'tel', 'timing', 'header_detail', 'address'], 'required'],
            [['exp_edu_detail'], 'string'],
            [['created_at'], 'safe'],
            [['name', 'phone', 'tel', 'timing'], 'string', 'max' => 255],
            [['header_detail', 'address'], 'string', 'max' => 500],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'exp_edu_detail' => 'Exp Edu Detail',
            'phone' => 'Phone',
            'tel' => 'Tel',
            'timing' => 'Timing',
            'header_detail' => 'Header Detail',
            'address' => 'Address',
            'created_at' => 'Create At',
        ];
    }

    public function beforeSave($insert)
    {
        if($insert){
            $this->created_at = date("Y-m-d H:i:s");
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
