<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "medicines".
 *
 * @property int $id
 * @property string $name
 * @property string $detail
 * @property string $created_at
 */
class Medicines extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'medicines';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'detail'], 'required'],
            [['detail'], 'string'],
            [['created_at'], 'safe'],
            [['name'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'detail' => 'Detail',
            'created_at' => 'Created At',
        ];
    }
    public function beforeSave($insert)
    {
        if($insert){
            $this->created_at = date("Y-m-d H:i:s");
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
