<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "patients".
 *
 * @property int $id
 * @property string $name
 * @property string|null $so_name
 * @property string|null $age
 * @property string|null $gender
 * @property string|null $phone
 * @property string|null $address
 * @property string|null $created_ate
 */
class Patients extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'patients';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['created_ate'], 'safe'],
            [['name', 'so_name', 'age', 'address'], 'string', 'max' => 255],
            [['gender'], 'string', 'max' => 10],
            [['phone'], 'string', 'max' => 20],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'so_name' => 'So/DO/WO',
            'age' => 'Age',
            'gender' => 'Gender',
            'phone' => 'Phone',
            'address' => 'Address',
            'created_ate' => 'Time',
        ];
    }
    public function beforeSave($insert)
    {
        if($insert){
            $this->created_ate = date("Y-m-d H:i:s");
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    /* public function beforeSave(){
         $this->created_ate = time();
         parent::beforeSave();
     }*/
}
