<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "patient_visits".
 *
 * @property int $id
 * @property int $patient_id
 * @property string|null $summery
 * @property int $status
 * @property string|null $created_at
 */
class PatientVisits extends \yii\db\ActiveRecord
{
    public $_status=[0=>'Pending',1=>'Processed'];
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'patient_visits';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['patient_id'], 'required'],
            [['patient_id', 'status'], 'integer'],
            [['summery'], 'string'],
            [['created_at'], 'safe'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'patient_id' => '',
            'summery' => 'Summery',
            'status' => 'Status',
            'created_at' => 'Created At',
        ];
    }
    public function beforeSave($insert)
    {
        if($insert){
            $this->created_at = date("Y-m-d H:i:s");
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
