<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "tokens".
 *
 * @property int $id
 * @property int $number
 * @property string|null $created_at
 * @property int|null $patient_id
 * @property string|null $status
 */
class Tokens extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'tokens';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['number'], 'required'],
            [['number', 'patient_id'], 'integer'],
            [['created_at'], 'safe'],
            [['status'], 'string', 'max' => 5],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'number' => 'Number',
            'created_at' => 'Created At',
            'patient_id' => 'Patient ID',
            'status' => 'Status',
        ];
    }

    public function beforeSave($insert)
    {
        if($insert){
            $this->created_at = date("Y-m-d H:i:s");
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
